### ISSUE TITLE
ZMNHBD1 i1 and i2 don't trigger flows

### ISSUE THREAD

**Issue by goyaweb** [athombv/com.qubino#14] opened 2017-02-19 11:26 UTC
Qubino Relay 2 switch z-wave plus
Added as an issue to track progress and possibilities.

**Comment by ivleth** [comment] 2017-07-10 12:09
any update in this issue? I guess the topic covers the same as when I toggle switch on, on the i1 connection the status in Homey isn't updated?

Thanks

**Comment by RobinBol** [comment] 2017-07-11 19:49
It is still on our radar, so it will be implemented in the near future.

**Comment by ivleth** [comment] 2017-07-11 19:50
Cheers, thanks

**Comment by hfaas** [comment] 2017-08-02 17:47
FYI: I've noticed some of the qubino devices (such as the ZMNHDD1) do not (yet) have full support of all inputs and noticed the following thread on a domoticz forum, mentioning extending the list of groups used as a solution.
This might speed up a solution?

https://www.domoticz.com/forum/viewtopic.php?t=9598

**Comment by IngmarHallie** [comment] 2017-11-15 11:29
The description for this topic is too narrow. i1 and i2 do not trigger flows because Homey doesn't process them after send by ZMNHBD1. So the functionality request is please add monitoring for i1 and i2 on Homey, when the inputs on ZMNHBD1 are changed because of connected electrical switches.

Eagerly awaiting this functionality. Any ideas for when this is planned?
Thanks!

**Comment by Steefph** [comment] 2017-12-09 09:01
Would it be possible to trigger on the raw data received? I'm trying to get the inputs I2 and I3 on the ZMNHDA2 to work but, don't understand how to work with the data received by Homey. In the z-wave log it shows a 0x....ff or 0x......00 value when triggered. Should it not be possible to trigger the event on this?

**Comment by JPe2** [comment] 2018-01-08 17:38
RobinBol added the enhancement label on 22 Feb 2017.
This not an enhancement, this is a BUG, we are waiting for a solution for more than TEN months now, together with other Qubino problems. When will there be seriously been working on this problem, please?

**Comment by kasteleman** [comment] 2018-02-09 11:11
Some additional info regarding the I2 on my ZMNHDA2:

Node[55]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x06013003ff
Node[55]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[1]},"Properties1":{"Instance":1,"Res":false},"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Parameter":{"type":"Buffer","data":[255]}}

**Comment by AndDym** [comment] 2018-04-24 13:18
Any news on this issue?

**Comment by JPe2** [comment] 2018-05-27 13:53
We are already more than 15 months waiting for this **basic** function, Athom please wake up (same problem with Fibaro FGS-221) The motto of Homey is:

> Connect all the Things
> Integrate your device or service with Homey

How should we do that without the Basic functions working correctly?

**Comment by titanium87** [comment] 2018-05-30 18:33
This can be such a big problem to fix?

**Comment by RobinBol** [comment] 2018-06-18 15:11
Hi! I just published a beta update of the Qubino app. It has been rewritten to SDKv2 and includes many minor issues. Also functionality for the available inputs has been added. Will close this issue for now, please let me know if you have any further questions or problems.

**Comment by JPe2** [comment] 2018-06-18 19:04
Great that you are working on this (long-lasting) problem, I have installed the Beta and did some tests.
Unfortunately, there are still some problems, 
First, the power indicator does not work anymore (no energie no energiem...
[ZMNHBD1-V2.zip](https://github.com/athombv/com.qubino/files/2112620/ZMNHBD1-V2.zip)
?)
![clipboarder 2018 06 18](https://user-images.githubusercontent.com/3833862/41552890-6e95e740-7330-11e8-8ab6-3912ececf3ce.png)
Second, when the relays are switched by switches connected to the i1 and i2 input of the device, the status of the relays (on/off) is not visible in the Homey app nor can be used in a flow.
Third, the text in the information is not according to the normally used description for NO and NC
![clipboarder 2018 06 18-002](https://user-images.githubusercontent.com/3833862/41553273-84e61172-7331-11e8-894b-7f3291447d85.png)
NO is indeed Normally Open, so no current can flow, so Closed (ON) when the relay is activated 
NC is indeed Normally Close, so current can flow, so Open (OFF) when the relay is activated

**Comment by kasteleman** [comment] 2018-06-19 06:57
Robin, Maybe driver.js missing?

Op ma 18 jun. 2018 om 21:04 schreef Jan <notifications@github.com>

**Comment by RobinBol** [comment] 2018-06-19 08:36
@JPe2 thanks for the quick feedback! Will look at it asap. With regard to the power meter, Qubino modules sometimes ignore the `METER_GET` command Homey sends to retrieve this value when Homey and/or the App boots. However, over time the module should report it by itself (only if the meter value has changed significantly), so maybe give it some time (with the connected device turned on so that it consumes energy). Anyway, I will see if I can reproduce your issue!

@kasteleman `driver.js` is momentarily (in this app) only relevant if the device supports custom Flow Cards like 'calibration' and input toggles.

**Comment by JPe2** [comment] 2018-06-19 09:55
2018-06-19T09:49:28.723Z | Node[94]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x0300
-- | --
2018-06-19T09:49:28.724Z | Node[94]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":"off/disable"}
2018-06-19T09:49:30.127Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000000000
2018-06-19T09:49:30.127Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,0]}}
2018-06-19T09:50:38.622Z | Node[94]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[94,1,37,1,255]}
2018-06-19T09:50:38.622Z | Node[94]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d5e012501ff
2018-06-19T09:50:42.037Z | Node[94]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
2018-06-19T09:50:42.037Z | Node[94]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
2018-06-19T09:50:43.068Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000600000
2018-06-19T09:50:43.069Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,96]}}
2018-06-19T09:52:22.498Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000610000
2018-06-19T09:52:22.498Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1}**,"Meter Value":{"type":"Buffer","data":[0,0,0,97]}}**

device seems to send power data!

**Comment by JPe2** [comment] 2018-06-19 11:02
When using the switch, connected to i1 (and also to i2 ) it seems only the ON is reported to Homey, not the OFF state:

2018-06-19T10:54:46.593Z | Node[94]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
-- | --
2018-06-19T10:54:46.593Z | Node[94]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
2018-06-19T10:54:48.017Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000040000
2018-06-19T10:54:48.017Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,4]}}
2018-06-19T10:54:51.631Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x0221340000000f0000
2018-06-19T10:54:51.632Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,15]}}
2018-06-19T10:54:52.636Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000000000
2018-06-19T10:54:52.637Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,0]}}
2018-06-19T10:55:02.667Z | Node[94]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
2018-06-19T10:55:02.668Z | Node[94]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
2018-06-19T10:55:03.688Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000600000
2018-06-19T10:55:03.689Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,96]}}
2018-06-19T10:55:43.873Z | Node[94]: Received application command for COMMAND_CLASS_METER, data: 0x0221340000005f0000
2018-06-19T10:55:43.874Z | Node[94]: [COMMAND_CLASS_METER] {"Meter Type (Raw)":{"type":"Buffer","data":[33]},"Properties1 (Raw)":{"type":"Buffer","data":[52]},"Properties1":{"Size":4,"Scale":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,95]}}

**Comment by RobinBol** [comment] 2018-06-19 12:55
Thanks for the additional information, I will come back to you after I managed to test/debug it myself, will re-open this issue for now since it is not properly resolved.

**Comment by JPe2** [comment] 2018-06-20 15:04
Extra info: the status above, ON and OFF, is transmitted with the association group-1 = 1
with the default association group-1 = 1.1 no status change is sent, while the relay is switching.
Also very strange is, when the switches are switched ON via Homey command, then only [255]},"Value":"on/enable" is sent when the connected switch is actuated, the OFF status is not sent!!

**Comment by JPe2** [comment] 2018-07-02 14:34
@RobinBol  I have installed the Qubino beta version v2.0.1 - 28.06.18, I have removed the QUBINO ZMNHDB1 device from the Homey z-wave net and after a long time, paired it again with Homey. The default association for group 1 is 1.1 now. Unfortunately, there is still no Power measurement
![clipboarder 2018 07 02](https://user-images.githubusercontent.com/3833862/42169558-5e0336d2-7e14-11e8-8df9-3e1191b0d2d4.png)
Also in the communication logging, I don't see the power meter values:

2018-07-02T13:55:29.134Z
Node[100]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[100,1,50,5]}
2018-07-02T13:55:29.134Z
Node[100]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d64013205
2018-07-02T13:56:25.185Z
Node[100]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[100,1,37,1,0]}
2018-07-02T13:56:25.185Z
Node[100]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d6401250100
2018-07-02T13:57:41.595Z
Node[100]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[100,1,37,1,255]}
2018-07-02T13:57:41.595Z
Node[100]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d64012501ff

When I change the association group 1 from 1.1 to 1, then in the communication-log, I do see power meter values:

018-07-02T14:07:34.404Z
Node[100]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_SET] {"type":"Buffer","data":[0]}
2018-07-02T14:07:34.404Z
Node[100]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x0100
2018-07-02T14:07:58.778Z
Node[100]: sendData to COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION, params 0x0401
2018-07-02T14:07:58.831Z
Node[100]: sendData to COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION, params 0x010101
2018-07-02T14:08:01.513Z
Node[100]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000000000
2018-07-02T14:08:01.514Z
Node[100]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,0]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":0}
2018-07-02T14:08:31.644Z
Node[100]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000000000
2018-07-02T14:08:31.645Z
Node[100]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,0]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":0}
2018-07-02T14:08:35.528Z
Node[100]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_SET] {"type":"Buffer","data":[0]}
2018-07-02T14:08:35.528Z
Node[100]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x0100
2018-07-02T14:08:35.880Z
Node[100]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_SET] {"type":"Buffer","data":[0]}
2018-07-02T14:08:35.880Z
Node[100]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x0100
2018-07-02T14:08:38.658Z
Node[100]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x0300
2018-07-02T14:08:38.658Z
Node[100]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":"off/disable"}
2018-07-02T14:08:41.857Z
Node[100]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_SET] {"type":"Buffer","data":[255]}
2018-07-02T14:08:41.857Z
Node[100]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x01ff
2018-07-02T14:08:45.692Z
Node[100]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
2018-07-02T14:08:45.693Z
Node[100]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
2018-07-02T14:08:46.712Z
Node[100]: Received application command for COMMAND_CLASS_METER, data: 0x0221340000005e0000
2018-07-02T14:08:46.713Z
Node[100]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,94]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":9.4}
2018-07-02T14:08:54.750Z
Node[100]: Received application command for COMMAND_CLASS_METER, data: 0x0221340000006a0000
2018-07-02T14:08:54.752Z
Node[100]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,106]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":10.6}
2018-07-02T14:09:01.784Z
Node[100]: Received application command for COMMAND_CLASS_METER, data: 0x0221340000005f0000
2018-07-02T14:09:01.785Z
Node[100]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,95]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":9.5}
In the Icons however, there is still no power indication.

**Comment by JPe2** [comment] 2018-07-02 15:06
@RobinBol  Looked at another installed device with two lamps connected to the two relays,

2018-07-02T14:47:06.701Z | Node[98]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_SET] {"type":"Buffer","data":[255]}
-- | --
2018-07-02T14:47:06.701Z | Node[98]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x01ff
2018-07-02T14:48:32.967Z | Node[98]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[98,1,37,1,255]}
2018-07-02T14:48:32.967Z | Node[98]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d62012501ff
2018-07-02T14:48:34.202Z | Node[98]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[98,2,37,1,255]}
2018-07-02T14:48:34.202Z | Node[98]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d62022501ff
2018-07-02T14:50:10.287Z | Node[98]: sendData to COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION, params 0x0401
2018-07-02T14:50:10.341Z | Node[98]: sendData to COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION, params 0x010101
2018-07-02T14:50:18.021Z | Node[98]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000bc0000
2018-07-02T14:50:18.022Z | Node[98]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,188]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":18.8}
2018-07-02T14:50:22.018Z | Node[98]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000c00000
2018-07-02T14:50:22.024Z | Node[98]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,192]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":19.2}
2018-07-02T14:50:23.019Z | Node[98]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000d00000
2018-07-02T14:50:23.020Z | Node[98]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,208]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":20.8}
2018-07-02T14:50:30.032Z | Node[98]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000bb0000
2018-07-02T14:50:30.032Z | Node[98]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,187]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":18.7}

The strange thing (for me) is that I don't see an indication for the 2 relays, seems it is seen as a 1-meter device?

**Comment by RobinBol** [comment] 2018-07-02 15:30
The only thing I can imagine is that you have a different (possibly older) firmware version on your device. Since we have the same device here and can not reproduce the issue, I am not sure if/how I can help you with this issue. Maybe you could contact Qubino support and ask for any known issues with your firmware and reference this issue?

**Comment by RobinBol** [comment] 2018-07-09 08:54
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2558

**Closed by RobinBol** 2018-07-09 08:54 UTC
Labels: enhancement
