### ISSUE TITLE
Support for flush shutters HCD1 and HOD

### ISSUE THREAD

**Issue by cbho** [athombv/com.qubino#20] opened 2017-09-16 13:33 UTC
What are the perspectives regarding support to the HCD1- and HOD1-modules?
Asked at the app store, but not sure if it is read?

By coincidence I found this:
https://github.com/clandmeter/com.qubino.shutter
What are the issues? Will it work if I buy a the "Flush shutter DC - Gen" that's in the stores now?
Regards,
Chr.

**Comment by Merlinuf** [comment] 2018-04-16 19:56
Have all development stopped on this?

**Comment by jogegot** [comment] 2018-05-12 11:11
Any update ??

**Comment by RobinBol** [comment] 2018-05-12 11:41
Closing as duplicate of https://github.com/athombv/com.qubino/issues/22. That issue has an answer to your question.

**Closed by RobinBol** 2018-05-12 11:41 UTC
Labels: enhancement
